name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: NPM install
      uses: bahmutov/npm-install@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: npm run build
      env:
        CI: false # TODO right now this fails if true because of linting rules
    # - name: Test
    #   run: npm test
    #   env:
    #     CI: true
